#!/usr/bin/env bash
# connectors/lib/status-render.sh — SP14 T-13.
#
# Generates ~/.claude/connectors/STATUS.md (or whatever --out path is passed)
# from connectors/manifest.json. Markdown table; one row per connector with
# columns: Connector | Last Run | Status | Auth | Next Run.
#
# OUTPUT CONTRACT (R-43):
#   Files written: $OUT (default: $CLAUDE_HOME/connectors/STATUS.md)
#   Schema-types: markdown (no schema)
#   Pre-write validation: connectors/manifest.json valid JSON OR empty fixture
#   Failure mode: BLOCK AND LOG. rc=2 bad invocation; rc=3 manifest unreadable
#                 (when --strict); empty connectors[] writes "No connectors
#                 configured" placeholder + rc=0.
#
# Usage:
#   bash status-render.sh [--manifest <path>] [--out <path>] [--strict]
#
# Exit codes: 0=success, 2=bad invocation, 3=manifest unreadable (--strict)

set -u

_diag() { printf 'status-render FAIL: %s\n' "$1" >&2; }

manifest="${CLAUDE_HOME:-$HOME/.claude}/connectors/manifest.json"
out="${CLAUDE_HOME:-$HOME/.claude}/connectors/STATUS.md"
strict=0

while [ $# -gt 0 ]; do
  case "$1" in
    --manifest) [ $# -lt 2 ] && { _diag "--manifest requires path"; exit 2; }; manifest="$2"; shift 2 ;;
    --out) [ $# -lt 2 ] && { _diag "--out requires path"; exit 2; }; out="$2"; shift 2 ;;
    --strict) strict=1; shift ;;
    -*) _diag "unknown flag: $1"; exit 2 ;;
    *) _diag "unexpected positional: $1"; exit 2 ;;
  esac
done

mkdir -p "$(dirname "$out")"
ts=$(date -u +%Y-%m-%dT%H:%M:%SZ)

if [ ! -r "$manifest" ]; then
  if [ "$strict" -eq 1 ]; then
    _diag "manifest not readable: $manifest"
    exit 3
  fi
  cat > "$out" <<EOF
# Connectors Status

_Last refreshed: ${ts}_

No connectors configured.
EOF
  exit 0
fi

connectors=$(jq -c '.connectors // []' "$manifest" 2>/dev/null) || {
  _diag "jq parse failed on manifest: $manifest"
  exit 3
}

n=$(printf '%s' "$connectors" | jq 'length' 2>/dev/null)
if [ "$n" = "0" ] || [ -z "$n" ]; then
  cat > "$out" <<EOF
# Connectors Status

_Last refreshed: ${ts}_

No connectors configured.
EOF
  exit 0
fi

# Build table
{
  printf '# Connectors Status\n\n'
  printf '_Last refreshed: %s_\n\n' "$ts"
  printf '| Connector | Last Run | Status | Auth | Next Run |\n'
  printf '|-----------|----------|--------|------|----------|\n'
  printf '%s' "$connectors" | jq -r '.[] | [
    .id,
    (.last_run // "—"),
    (.last_status // "—"),
    (
      if .auth_status == "expired" then "**RECONNECT REQUIRED**"
      elif .auth_status == "pending" then "pending"
      elif .auth_status == "connected" then
        (if .auth_expires_at then "connected (exp " + .auth_expires_at + ")" else "connected" end)
      else "—" end
    ),
    (.schedule // "—")
  ] | "| " + join(" | ") + " |"'
  printf '\n_Generated by SP14 T-13 status-render.sh._\n'
} > "$out"

exit 0
