#!/usr/bin/env bash
# tests/sp14-hooks-branch1-classD-writer-scopemiss.sh
#
# SP14 T-18 fixture — pre-write-guard.sh Branch #3 excluded_paths (librarian-
# owned derived artifacts). Permutation: SCOPE-MISS (the vault-writer
# frontmatter validation explicitly excludes _index.md and _overlap-matrix.md
# per vault-writer.md.json :: excluded_paths).
#
# Inventory-labeled "Class D writer-scopemiss"; substrate semantics live
# in Branch #3 (line 950-953), not Branch #1. Substrate behavior: write
# to Vault Writers/_index.md or _overlap-matrix.md → branch #3 emits no
# fragment AND no deny. Downstream blocks (3-tier vault schema) may emit
# their own context, but Branch #3 itself is silent.
#
# Filename retained per dispatch brief inventory.

set -u
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/sp14-hooks-setup.sh"

setup_jailed_home
stage_substrate

printf '[fixture] Branch #3 excluded_paths — Vault Writers/_index.md (scope-miss)\n'

# Target: librarian-managed derived artifact.
target="$VAULT_ROOT/Vault Writers/_index.md"
mkdir -p "$(dirname "$target")"

# Content: librarian-style auto-generated index. Frontmatter intentionally
# minimal (would FAIL Branch #3 vault-writer validation if it ran).
content="---
type: writer-catalog
title: Writers — Index
updated: 2026-05-20
---

# Writers — Index

(Auto-generated by librarian writers-index-refresh.)
"

payload=$(build_write_payload "$target" "$content")
out=$(printf '%s' "$payload" | bash "$HOME/.claude/hooks/pre-write-guard.sh" 2>/dev/null)
rc=$?

assert_rc "exit code is 0 (allow)" 0 "$rc"
# Branch #3 deny message MUST NOT appear (scope-miss via excluded_paths).
assert_not_contains "Branch #3 schema-violation deny NOT present (excluded path)" "$out" "SP14 Branch #3"
assert_not_contains "no Vault Writers/ schema violation fragment" "$out" "Vault Writers/ schema violation"

# Same scope-miss for _overlap-matrix.md.
target2="$VAULT_ROOT/Vault Writers/_overlap-matrix.md"
content2="---
type: writer-overlap-matrix
title: Writers — Overlap Matrix
---

| Writer | Destination | Source |
|--------|-------------|--------|
"
payload2=$(build_write_payload "$target2" "$content2")
out2=$(printf '%s' "$payload2" | bash "$HOME/.claude/hooks/pre-write-guard.sh" 2>/dev/null)
rc2=$?

assert_rc "_overlap-matrix.md write exit 0" 0 "$rc2"
assert_not_contains "_overlap-matrix.md not blocked by Branch #3" "$out2" "SP14 Branch #3"

fixture_summary
